"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LargeKnowledgeGraph from "../components/LargeKnowledgeGraph";
import ThemeToggle from "../components/ThemeToggle";
import Link from "next/link";
import WikiHeadingsLinks from "../components/WikiHeadingsLinks";
import WikiNav from "../components/WikiNav";
import { useState, useMemo } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Removed export const metadata due to Next.js client component restriction
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const topics = [
  { slug: "science-tree", title: "Science Tree" },
  { slug: "chemistry", title: "Chemistry" },
  { slug: "biology", title: "Biology" },
  { slug: "physics", title: "Physics" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [navOpen, setNavOpen] = useState(true);

  // Determine grid columns for wiki-layout based on navOpen
  const gridColumns = navOpen ? "260px 1fr 340px" : "0 1fr 340px";

  // Topics and subtopics for global search
  const allTopics = useMemo(() => [
    { slug: "science-tree", title: "Science Tree" },
    { slug: "chemistry", title: "Chemistry" },
    { slug: "biology", title: "Biology" },
    { slug: "physics", title: "Physics" },
    // Add more here if you expand
  ], []);
  const [search, setSearch] = useState("");
  const filteredTopics = search.trim()
    ? allTopics.filter(t => t.title.toLowerCase().includes(search.trim().toLowerCase()) || t.slug.toLowerCase().includes(search.trim().toLowerCase()))
    : allTopics;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="wiki-layout" style={{ gridTemplateColumns: gridColumns }}>
          <WikiNav navOpen={navOpen} setNavOpen={setNavOpen} ThemeToggle={ThemeToggle} />
          <main className="wiki-main">{children}</main>
          <aside className="wiki-graph">
            <LargeKnowledgeGraph />
            <div className="wiki-related">
              <WikiHeadingsLinks />
            </div>
          </aside>
        </div>
      </body>
    </html>
  );
}
