import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import KnowledgeGraph from "../components/KnowledgeGraph";
import ThemeToggle from "../components/ThemeToggle";
import Link from "next/link";
import WikiHeadingsLinks from "../components/WikiHeadingsLinks";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const topics = [
  { slug: "science-tree", title: "Science Tree" },
  { slug: "chemistry", title: "Chemistry" },
  { slug: "biology", title: "Biology" },
  { slug: "physics", title: "Physics" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="wiki-layout">
          <aside className="wiki-nav">
            <ThemeToggle />
            <nav>
              <h2 className="wiki-nav-title">Topics</h2>
              <ul className="wiki-nav-list">
                {topics.map(topic => (
                  <li key={topic.slug}>
                    <Link href={`/notes/${topic.slug}`} className="wiki-link-main">
                      {topic.title}
                    </Link>
                  </li>
                ))}
              </ul>
            </nav>
          </aside>
          <main className="wiki-main">{children}</main>
          <aside className="wiki-graph">
            <KnowledgeGraph />
            <div className="wiki-related">
              <WikiHeadingsLinks />
            </div>
          </aside>
        </div>
      </body>
    </html>
  );
}
