"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import KnowledgeGraph from "../components/KnowledgeGraph";
import ThemeToggle from "../components/ThemeToggle";
import Link from "next/link";
import WikiHeadingsLinks from "../components/WikiHeadingsLinks";
import { useState } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Removed export const metadata due to Next.js client component restriction
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const topics = [
  { slug: "science-tree", title: "Science Tree" },
  { slug: "chemistry", title: "Chemistry" },
  { slug: "biology", title: "Biology" },
  { slug: "physics", title: "Physics" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [navOpen, setNavOpen] = useState(true);

  // Determine grid columns for wiki-layout based on navOpen
  const gridColumns = navOpen ? "260px 1fr 340px" : "0 1fr 340px";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="wiki-layout" style={{ gridTemplateColumns: gridColumns }}>
          <aside className={`wiki-nav${navOpen ? "" : " nav-hidden"}`} style={{ position: "relative" }}>
            <button
              className="wiki-nav-toggle"
              aria-label={navOpen ? "Hide navigation" : "Show navigation"}
              onClick={() => setNavOpen((open) => !open)}
              style={{
                position: "absolute",
                top: 12,
                left: navOpen ? "100%" : 8,
                transform: navOpen ? "translateX(-100%)" : "none",
                zIndex: 50,
                marginLeft: navOpen ? 0 : 0,
                background: "#fff",
                border: "1px solid #ccc",
                borderRadius: "50%",
                width: 32,
                height: 32,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                fontSize: 20,
                cursor: "pointer",
                boxShadow: "0 1px 4px 0 #0001",
                transition: "left 0.3s, background 0.2s, color 0.2s"
              }}
            >
              {navOpen ? "←" : "→"}
            </button>
            <div style={{ display: navOpen ? "block" : "none" }}>
              <ThemeToggle />
              <nav>
                <h2 className="wiki-nav-title">Topics</h2>
                <ul className="wiki-nav-list">
                  {topics.map(topic => (
                    <li key={topic.slug}>
                      <Link href={`/notes/${topic.slug}`} className="wiki-link-main">
                        {topic.title}
                      </Link>
                    </li>
                  ))}
                </ul>
              </nav>
            </div>
          </aside>
          <main className="wiki-main">{children}</main>
          <aside className="wiki-graph">
            <KnowledgeGraph />
            <div className="wiki-related">
              <WikiHeadingsLinks />
            </div>
          </aside>
        </div>
      </body>
    </html>
  );
}
